'use strict';
(function objectWrongMachine(){
const pan=window.ThePan||{};if(pan.analytics)pan.analytics.configure('object_wrong_machine','v1');const $=id=>document.getElementById(id),canvas=$('objectWrongCanvas'),ctx=canvas.getContext('2d'),imageInput=$('imageInput'),objInput=$('objInput'),drop=$('dropZone'),status=$('fileStatus'),error=$('fileError'),meta=$('objectMeta'),modeMeta=$('modeMeta'),renderMode=$('renderMode'),transparent=$('transparent'),spin=$('spin'),recordButton=$('recordButton'),recordStatus=$('recordStatus');let source=null,objModel=null,wobble=0,raf,last=0,recording=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function n(id){return Number($(id).value)}function err(s){error.textContent=s;error.hidden=false}function clear(){error.hidden=true;error.textContent=''}function outputs(){document.querySelectorAll('input[type=range]').forEach(i=>{const o=document.querySelector(`output[for="${i.id}"]`);if(o)o.value=i.value})}
function demo(){const c=document.createElement('canvas');c.width=c.height=900;const x=c.getContext('2d');x.fillStyle='#efeee7';x.fillRect(0,0,900,900);x.fillStyle='#ff3b1f';x.beginPath();x.arc(450,420,245,0,Math.PI*2);x.fill();x.fillStyle='#111';x.font='900 112px sans-serif';x.textAlign='center';x.fillText('WRONG',450,455);x.strokeStyle='#3857ff';x.lineWidth=28;x.strokeRect(190,160,520,520);source=c;render()}
async function loadImage(file){clear();if(!file||!file.type.startsWith('image/')){err('DROP A JPG, PNG, WEBP OR GIF.');return}try{const bmp=await createImageBitmap(file);source=bmp;objModel=null;status.textContent='PHOTO LOADED / LOCAL ONLY';meta.textContent=`PHOTO / ${bmp.width} × ${bmp.height} / FAKE DEPTH`;render();pan.analytics&&pan.analytics.track('tool_input_ready',{input_type:'image'})}catch(e){err('COULD NOT READ THAT IMAGE.')}}
function parseOBJ(text){const v=[],f=[];for(const raw of text.split(/\r?\n/)){const l=raw.trim();if(l.startsWith('v ')){const p=l.split(/\s+/).slice(1,4).map(Number);if(p.every(Number.isFinite))v.push(p)}else if(l.startsWith('f ')){const q=l.split(/\s+/).slice(1).map(t=>parseInt(t,10)-1).filter(Number.isInteger);if(q.length>2)f.push(q)}}if(v.length<3||!f.length)throw Error('OBJ NEEDS VERTICES + FACES.');const max=Math.max(...v.flat().map(Math.abs))||1;return{v:v.map(p=>p.map(q=>q/max)),f}}
async function loadOBJ(file){try{objModel=parseOBJ(await file.text());source=null;status.textContent='OBJ LOADED / NERD DOOR';meta.textContent=`OBJ / ${objModel.v.length} VERTICES / ${objModel.f.length} FACES`;render()}catch(e){err(e.message)}}
function quad(){const w=canvas.width,h=canvas.height,s=n('scale')/100*.72,ox=w/2+n('offsetX')/100*w*.3,oy=h/2+n('offsetY')/100*h*.3,rx=(n('rotateX')+wobble)*Math.PI/180,ry=(n('rotateY')+wobble*.7)*Math.PI/180,rz=n('rotateZ')*Math.PI/180,depth=n('depth')/100;return[[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,y])=>{let z=x*Math.sin(ry)+y*Math.sin(rx),xx=x*Math.cos(ry),yy=y*Math.cos(rx);const persp=1/(1+z*depth*.42),X=xx*Math.cos(rz)-yy*Math.sin(rz),Y=xx*Math.sin(rz)+yy*Math.cos(rz);return[ox+X*w*.42*s*persp,oy+Y*h*.42*s*persp]})}
function drawPhoto(){if(!source)return;const p=quad(),off=document.createElement('canvas');off.width=canvas.width;off.height=canvas.height;off.getContext('2d').drawImage(source,0,0,off.width,off.height);ctx.save();ctx.beginPath();ctx.moveTo(...p[0]);p.slice(1).forEach(q=>ctx.lineTo(...q));ctx.closePath();ctx.clip();const minX=Math.min(...p.map(q=>q[0])),maxX=Math.max(...p.map(q=>q[0])),minY=Math.min(...p.map(q=>q[1])),maxY=Math.max(...p.map(q=>q[1]));ctx.drawImage(off,minX,minY,maxX-minX,maxY-minY);ctx.restore();const m=renderMode.value,d=n('density');if(m==='pixel'){const small=document.createElement('canvas');small.width=small.height=Math.max(20,220-d*10);small.getContext('2d').drawImage(canvas,0,0,small.width,small.height);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(small,0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=true}else if(m==='dots'||m==='blocks'||m==='wire'){const img=ctx.getImageData(0,0,canvas.width,canvas.height);ctx.clearRect(0,0,canvas.width,canvas.height);const step=Math.max(10,46-d*2);for(let y=step/2;y<canvas.height;y+=step)for(let x=step/2;x<canvas.width;x+=step){const i=(Math.floor(y)*canvas.width+Math.floor(x))*4;if(img.data[i+3]<20)continue;const lum=(img.data[i]+img.data[i+1]+img.data[i+2])/765;if(m==='wire'){if(lum<.55){ctx.fillStyle=$('inkA').value;ctx.fillRect(x,y,2,2)}}else{ctx.fillStyle=lum<.34?$('inkA').value:lum<.67?$('inkB').value:$('inkC').value;if(m==='dots'){ctx.beginPath();ctx.arc(x,y,step*.32,0,Math.PI*2);ctx.fill()}else ctx.fillRect(x-step*.32,y-step*.32,step*.64,step*.64)}}}}
function drawOBJ(){const pts=objModel.v.map(([x,y,z])=>{const a=(n('rotateY')+wobble)*Math.PI/180,b=n('rotateX')*Math.PI/180;let X=x*Math.cos(a)+z*Math.sin(a),Z=-x*Math.sin(a)+z*Math.cos(a),Y=y*Math.cos(b)-Z*Math.sin(b);return[canvas.width/2+X*canvas.width*.28*n('scale')/100,canvas.height/2-Y*canvas.height*.28*n('scale')/100]});ctx.strokeStyle=$('inkA').value;ctx.lineWidth=3;for(const f of objModel.f){ctx.beginPath();f.forEach((i,k)=>k?ctx.lineTo(...pts[i]):ctx.moveTo(...pts[i]));ctx.closePath();ctx.stroke()}}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);if(!transparent.checked){ctx.fillStyle=$('background').value;ctx.fillRect(0,0,canvas.width,canvas.height)}if(objModel)drawOBJ();else drawPhoto();modeMeta.textContent=renderMode.options[renderMode.selectedIndex].text}
function reset(){const v={rotateX:-12,rotateY:18,rotateZ:0,scale:82,offsetX:0,offsetY:0,density:8,depth:58,light:74};Object.entries(v).forEach(([k,x])=>$(k).value=x);renderMode.value='solid';spin.checked=false;wobble=0;outputs();render()}
function wrong(){const modes=['solid','pixel','dots','blocks','wire'];$('rotateX').value=Math.round(Math.random()*80-40);$('rotateY').value=Math.round(Math.random()*80-40);$('rotateZ').value=Math.round(Math.random()*70-35);$('depth').value=Math.round(Math.random()*80+15);$('density').value=Math.round(Math.random()*14+3);renderMode.value=modes[Math.floor(Math.random()*modes.length)];outputs();render()}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
function save(){render();canvas.toBlob(b=>{downloadBlob(b,'the-pan-object-wrong.png');pan.analytics&&pan.analytics.track('export_complete',{export_type:'png'})},'image/png')}
function recordingMime(){if(!window.MediaRecorder)return null;const choices=[['video/mp4;codecs=avc1','mp4'],['video/mp4','mp4'],['video/webm;codecs=vp9','webm'],['video/webm;codecs=vp8','webm'],['video/webm','webm']];for(const [mime,ext] of choices)if(MediaRecorder.isTypeSupported(mime))return{mime,ext};return null}
function recordMotion(){if(recording)return;const fmt=recordingMime();if(!canvas.captureStream||!fmt){recordStatus.textContent='MOTION RECORDING NOT SUPPORTED HERE';return}const seconds=n('recordSeconds'),stream=canvas.captureStream(30),chunks=[];let rec;try{rec=new MediaRecorder(stream,{mimeType:fmt.mime,videoBitsPerSecond:8000000})}catch(e){recordStatus.textContent='RECORDER COULD NOT START';return}recording=true;recordButton.disabled=true;recordButton.textContent='RECORDING…';recordStatus.textContent=`RECORDING ${seconds} SEC · ${fmt.ext.toUpperCase()}`;const oldSpin=spin.checked;spin.checked=true;rec.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};rec.onerror=()=>{recordStatus.textContent='RECORDING FAILED'};rec.onstop=()=>{spin.checked=oldSpin;recording=false;recordButton.disabled=false;recordButton.textContent='REC MOTION';stream.getTracks().forEach(t=>t.stop());if(chunks.length){const blob=new Blob(chunks,{type:fmt.mime});downloadBlob(blob,`the-pan-object-wrong-${seconds}s.${fmt.ext}`);recordStatus.textContent=`DONE · ${fmt.ext.toUpperCase()} EXPORTED`;pan.analytics&&pan.analytics.track('export_complete',{export_type:fmt.ext,duration_seconds:seconds})}else recordStatus.textContent='NO VIDEO DATA'};rec.start(250);setTimeout(()=>{if(rec.state!=='inactive')rec.stop()},seconds*1000)}
['rotateX','rotateY','rotateZ','scale','offsetX','offsetY','density','depth','light','background','inkA','inkB','inkC'].forEach(id=>$(id).addEventListener('input',()=>{outputs();render()}));renderMode.addEventListener('change',render);transparent.addEventListener('change',render);$('resetButton').onclick=reset;$('randomButton').onclick=wrong;$('exportButton').onclick=save;recordButton.onclick=recordMotion;imageInput.onchange=()=>loadImage(imageInput.files[0]);objInput.onchange=()=>loadOBJ(objInput.files[0]);['dragenter','dragover'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add('is-dragging')}));['dragleave','drop'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('is-dragging')}));drop.addEventListener('drop',e=>loadImage(e.dataTransfer.files[0]));function animate(t){if((spin.checked||recording)&&!reduced){wobble=Math.sin(t*.0012)*12;render()}last=t;raf=requestAnimationFrame(animate)}document.querySelectorAll('[data-current-year]').forEach(x=>x.textContent=new Date().getFullYear());outputs();demo();const initialFmt=recordingMime();recordStatus.textContent=initialFmt?`READY TO RECORD · ${initialFmt.ext.toUpperCase()}`:'MOTION RECORDING UNSUPPORTED';raf=requestAnimationFrame(animate)
})();