'use strict';

(function objectWrongMachine(){
  const pan=window.ThePan||{};
  if(pan.analytics) pan.analytics.configure('object_wrong_machine','v0');

  const $=(id)=>document.getElementById(id);
  const el={canvas:$('objectWrongCanvas'),input:$('objInput'),drop:$('dropZone'),status:$('fileStatus'),error:$('fileError'),meta:$('objectMeta'),mode:$('modeMeta'),reset:$('resetButton'),random:$('randomButton'),export:$('exportButton'),spin:$('spin'),renderMode:$('renderMode'),transparent:$('transparent')};
  const controls=['rotateX','rotateY','rotateZ','scale','offsetX','offsetY','density','depth','light','background','inkA','inkB','inkC'];
  const ctx=el.canvas.getContext('2d');
  const prefersReducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  let spinAngle=0,raf=0,last=0;
  const demo={vertices:[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]],faces:[[0,1,2,3],[4,7,6,5],[0,4,5,1],[1,5,6,2],[2,6,7,3],[4,0,3,7]]};
  let model=normalizeModel(demo);
  function num(id){return Number($(id).value)} function hexRgb(hex){const n=parseInt(hex.slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255]} function mix(a,b,t){return `rgb(${a.map((v,i)=>Math.round(v+(b[i]-v)*t)).join(',')})`}
  function showError(message){el.error.textContent=message;el.error.hidden=false;if(pan.analytics)pan.analytics.track('tool_error',{error_type:'obj_parse'});} function clearError(){el.error.hidden=true;el.error.textContent='';}
  function parseOBJ(text){const vertices=[],faces=[];for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(line.startsWith('v ')){const p=line.split(/\s+/).slice(1,4).map(Number);if(p.length===3&&p.every(Number.isFinite))vertices.push(p);}else if(line.startsWith('f ')){const ids=line.split(/\s+/).slice(1).map(token=>parseInt(token.split('/')[0],10)).map(i=>i<0?vertices.length+i:i-1).filter(i=>Number.isInteger(i));if(ids.length>=3)faces.push(ids);}}if(vertices.length<3||faces.length<1)throw new Error('OBJ needs vertices and faces.');if(vertices.length>50000||faces.length>50000)throw new Error('OBJ is too dense for V0. Keep it under 50k vertices/faces.');return normalizeModel({vertices,faces});}
  function normalizeModel(source){const xs=source.vertices.map(v=>v[0]),ys=source.vertices.map(v=>v[1]),zs=source.vertices.map(v=>v[2]);const center=[(Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2,(Math.min(...zs)+Math.max(...zs))/2];const shifted=source.vertices.map(v=>v.map((n,i)=>n-center[i]));let max=0;for(const v of shifted)max=Math.max(max,Math.abs(v[0]),Math.abs(v[1]),Math.abs(v[2]));const scale=max||1;return{vertices:shifted.map(v=>v.map(n=>n/scale)),faces:source.faces};}
  function rotate(v,rx,ry,rz){let[x,y,z]=v;let c=Math.cos(rx),s=Math.sin(rx);[y,z]=[y*c-z*s,y*s+z*c];c=Math.cos(ry);s=Math.sin(ry);[x,z]=[x*c+z*s,-x*s+z*c];c=Math.cos(rz);s=Math.sin(rz);[x,y]=[x*c-y*s,x*s+y*c];return[x,y,z];}
  function projected(){const d=Math.PI/180,rx=num('rotateX')*d,ry=(num('rotateY')+spinAngle)*d,rz=num('rotateZ')*d;const sc=num('scale')/100*el.canvas.width*.34,ox=el.canvas.width/2+num('offsetX')/100*el.canvas.width*.32,oy=el.canvas.height/2+num('offsetY')/100*el.canvas.height*.32;return model.vertices.map(v=>{const r=rotate(v,rx,ry,rz);const perspective=1/(1+r[2]*num('depth')/260);return{x:ox+r[0]*sc*perspective,y:oy-r[1]*sc*perspective,z:r[2]};});}
  function faceData(points,face){const p=face.map(i=>points[i]).filter(Boolean);if(p.length<3)return null;const a=p[0],b=p[1],c=p[2];const ux=b.x-a.x,uy=b.y-a.y,uz=b.z-a.z,vx=c.x-a.x,vy=c.y-a.y,vz=c.z-a.z;const nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx;const mag=Math.hypot(nx,ny,nz)||1;return{p,z:p.reduce((sum,q)=>sum+q.z,0)/p.length,light:Math.max(0,(nx*.25+ny*-.55+nz*.8)/mag)};}
  function pathFace(p){ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);for(let i=1;i<p.length;i++)ctx.lineTo(p[i].x,p[i].y);ctx.closePath();}
  function drawSolid(faces){const a=hexRgb($('inkA').value),b=hexRgb($('inkB').value),c=hexRgb($('inkC').value),power=num('light')/100;for(const f of faces){const t=Math.max(0,Math.min(1,(f.light*.65+.35)*power));pathFace(f.p);ctx.fillStyle=t<.5?mix(a,b,t*2):mix(b,c,(t-.5)*2);ctx.fill();ctx.strokeStyle='rgba(0,0,0,.16)';ctx.lineWidth=1.5;ctx.stroke();}}
  function drawWire(faces){ctx.strokeStyle=$('inkA').value;ctx.lineWidth=Math.max(1,num('density')/5);for(const f of faces){pathFace(f.p);ctx.stroke();}} function drawDots(points){const density=num('density'),r=2+density*.48;ctx.fillStyle=$('inkB').value;for(let i=0;i<points.length;i+=Math.max(1,Math.floor(14-density*.65))){const p=points[i];ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();}} function drawBlocks(points){const density=num('density'),size=3+density*1.5;for(let i=0;i<points.length;i+=Math.max(1,Math.floor(12-density*.55))){const p=points[i];ctx.fillStyle=i%3===0?$('inkB').value:i%3===1?$('inkC').value:$('inkA').value;ctx.fillRect(Math.round(p.x/size)*size,Math.round(p.y/size)*size,size,size);}}
  function renderPixel(){const density=num('density');const small=document.createElement('canvas');small.width=Math.max(28,Math.round(240-density*9));small.height=small.width;const sctx=small.getContext('2d');sctx.imageSmoothingEnabled=true;sctx.drawImage(el.canvas,0,0,small.width,small.height);ctx.clearRect(0,0,el.canvas.width,el.canvas.height);if(!el.transparent.checked){ctx.fillStyle=$('background').value;ctx.fillRect(0,0,el.canvas.width,el.canvas.height);}ctx.imageSmoothingEnabled=false;ctx.drawImage(small,0,0,el.canvas.width,el.canvas.height);ctx.imageSmoothingEnabled=true;}
  function render(){const w=el.canvas.width,h=el.canvas.height;ctx.clearRect(0,0,w,h);if(!el.transparent.checked){ctx.fillStyle=$('background').value;ctx.fillRect(0,0,w,h);}const points=projected();const faces=model.faces.map(face=>faceData(points,face)).filter(Boolean).sort((a,b)=>a.z-b.z);const mode=el.renderMode.value;if(mode==='solid'||mode==='pixel')drawSolid(faces);else if(mode==='wire')drawWire(faces);else if(mode==='dots'){drawWire(faces);drawDots(points);}else if(mode==='blocks'){drawWire(faces);drawBlocks(points);}if(mode==='pixel')renderPixel();el.mode.textContent=mode.toUpperCase();}
  function updateOutputs(){document.querySelectorAll('input[type="range"]').forEach(input=>{const out=document.querySelector(`output[for="${input.id}"]`);if(out)out.value=input.value;});}
  async function loadFile(file){clearError();if(!file||!file.name.toLowerCase().endsWith('.obj')){showError('CHOOSE A .OBJ FILE.');return;}try{el.status.textContent='READING LOCAL OBJ…';const text=await file.text();model=parseOBJ(text);el.status.textContent='OBJ LOADED / LOCAL ONLY';el.meta.textContent=`OBJECT / ${model.vertices.length} VERTICES / ${model.faces.length} FACES`;render();if(pan.analytics)pan.analytics.track('tool_input_ready',{input_type:'obj'});}catch(error){showError(error.message||'COULD NOT READ OBJ.');el.status.textContent='DEMO OBJECT REMAINS ACTIVE';}}
  function reset(){const values={rotateX:-18,rotateY:32,rotateZ:0,scale:76,offsetX:0,offsetY:0,density:8,depth:68,light:74};for(const[id,value]of Object.entries(values))$(id).value=value;el.renderMode.value='solid';el.spin.checked=false;spinAngle=0;updateOutputs();render();} function scramble(){const pick=(a)=>a[Math.floor(Math.random()*a.length)];$('rotateX').value=Math.round(Math.random()*120-60);$('rotateY').value=Math.round(Math.random()*360-180);$('rotateZ').value=Math.round(Math.random()*70-35);$('density').value=Math.round(Math.random()*13+4);$('depth').value=Math.round(Math.random()*80+15);el.renderMode.value=pick(['solid','dots','blocks','wire','pixel']);updateOutputs();render();}
  function exportPNG(){render();el.canvas.toBlob(blob=>{if(!blob){showError('PNG EXPORT FAILED.');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='the-pan-object-wrong.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);if(pan.analytics)pan.analytics.track('export_complete',{export_type:'png'});},'image/png');}
  for(const id of controls){$(id).addEventListener('input',()=>{updateOutputs();render();});}el.renderMode.addEventListener('change',render);el.transparent.addEventListener('change',render);el.spin.addEventListener('change',()=>{if(prefersReducedMotion&&el.spin.checked)el.spin.checked=false;});el.reset.addEventListener('click',reset);el.random.addEventListener('click',scramble);el.export.addEventListener('click',exportPNG);el.input.addEventListener('change',()=>loadFile(el.input.files[0]));for(const type of ['dragenter','dragover'])el.drop.addEventListener(type,e=>{e.preventDefault();el.drop.classList.add('is-dragging');});for(const type of ['dragleave','drop'])el.drop.addEventListener(type,e=>{e.preventDefault();el.drop.classList.remove('is-dragging');});el.drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));
  function animate(time){if(el.spin.checked&&!prefersReducedMotion){const dt=Math.min(40,time-last||16);spinAngle=(spinAngle+dt*.025)%360;render();}last=time;raf=requestAnimationFrame(animate);}window.addEventListener('beforeunload',()=>cancelAnimationFrame(raf));document.querySelectorAll('[data-current-year]').forEach(node=>node.textContent=new Date().getFullYear());updateOutputs();render();raf=requestAnimationFrame(animate);
})();
